columns: ['OPEN', 'HIGH', 'LOW', 'CLOSE', 'Price_return', 'Open_return',
       'High_return', 'Low_return', 'SMA_10', 'SMA_30', 'EMA_10', 'EMA_30',
       'Volatility_10', 'Volatility_30', 'daily_return', 'y_diff',
       'SMA_2_diff', 'EMA_2_diff', 'Volatility_2_diff', 'SMA_7_diff',
       'EMA_7_diff', 'Volatility_7_diff', 'SMA_30_diff', 'EMA_30_diff',
       'Volatility_30_diff', 'SMA_60_diff', 'EMA_60_diff',
       'Volatility_60_diff', 'SMA_2', 'EMA_2', 'Volatility_2', 'SMA_7',
       'EMA_7', 'Volatility_7', 'SMA_60', 'EMA_60', 'Volatility_60']

data_path: "data/xauusd/xauusd_7h_2009.csv"  # Path to CSV file
date_col: "DATE"  # Column name for dates
start_date: ""  # Start date for filtering (empty for all)
end_date: ""  # End date for filtering (empty for all)
target_col: "LOW"  # Primary target column
problem_type: "univariate"  # ["univariate", "multivariate"]
test_size: 30  # Number of samples for testing
model_dir: "models"  # Directory to save models
log_dir: "logs"  # Directory for logs
n_steps: 60  # Lookback window size
m_steps: 5  # Forecast horizon
horizon: 60  # Maximum forecast steps
split_ratio: 0.9  # Train/validation split ratio [0.1-0.95]
exclude_cols: []  # Columns to exclude from dataset
input_features: ['LOW','y_diff','Low_return','Price_return','Volatility_2_diff','EMA_2_diff']  # Input features
target_features: ['y_diff','Low_return','Price_return']  # Target features
batch_size: 32  # [16, 32, 64, 128, 256]
epochs: 80  # Training epochs [10-500]
seasonal_period: 15  # Seasonal period for decomposition [1-365]
lags: [2, 7, 30, 60]  # Lag periods for features
rolling_windows: [2, 7, 30, 60]  # Rolling window sizes
xgb_future_method: 'recursive'  # ['recursive', 'direct', 'multioutput']
inference_batches: 1  # Number of batches for inference
watermark_path: 'vrz.png'  # Path to watermark image
watermark_size: 70  # Watermark size in pixels
watermark_opacity: 0.1  # Watermark opacity [0-1]
records: 9000  # Max records to load
cache:
  enabled: true  # [true, false]
  directory: "./joblib_cache"  # Cache directory
  size_limit_mb: 12480  # Cache size limit in MB

# N-BEATS model configuration
nbeats:
  model_type: "interpretable"  # ["interpretable", "blackbox"]
  hidden_size: 512  # [128, 256, 512, 1024]
  epochs: 100  # [10-500]
  batch_size: 32  # [16, 32, 64, 128]
  learning_rate: 0.001  # [0.00001, 0.0001, 0.001, 0.01, 0.1]
  patience_es: 20  # Early stopping patience [1-100]
  patience_rlr: 10  # ReduceLROnPlateau patience [1-50]
  stacks_config:
    - type: "trend"  # ["trend", "seasonality"]
      num_blocks: 3  # [1-10]
      hidden_size: 256  # [64, 128, 256, 512]
      degree: 3  # Polynomial degree [1-5]
    - type: "seasonality"  # ["trend", "seasonality"]
      num_blocks: 3  # [1-10]
      hidden_size: 256  # [64, 128, 256, 512]
      num_harmonics: 6  # [1-20]
  blackbox_config:
    num_blocks: 4  # [1-20]
    num_layers: 4  # [1-10]
  device: "cpu"  # ["cpu", "cuda"]

# SVR model configuration
svr:
  kernel: "rbf"  # ["linear", "poly", "rbf", "sigmoid"]
  C: 1.0  # Regularization parameter [0.01, 0.1, 1, 10, 100, 1000]
  epsilon: 0.1  # Epsilon in epsilon-SVR [0.01, 0.05, 0.1, 0.2, 0.5]
  gamma: "scale"  # ["scale", "auto"] or float value [0.001, 0.01, 0.1, 1, 10]
  max_iter: 10000  # Maximum iterations [-1, 100, 1000, 10000, 50000]
  degree: 3  # Degree for polynomial kernel [1, 2, 3, 4, 5]
  coef0: 0.0  # Independent term in kernel [0.0, 0.1, 0.5, 1.0]
  shrinking: true  # [true, false]
  tol: 0.001  # Tolerance for stopping criterion [0.0001, 0.001, 0.01, 0.1]
  cache_size: 200  # Cache size in MB [100, 200, 500, 1000]
  verbose: false  # [true, false]